# Generated by Django 2.2.1 on 2019-07-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_barrankcsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrankcsv',
            name='address',
            field=models.CharField(max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='barrankcsv',
            name='kanaTitle',
            field=models.CharField(max_length=150, verbose_name='kanaTitle'),
        ),
        migrations.AlterField(
            model_name='barrankcsv',
            name='promotion',
            field=models.TextField(verbose_name='promotion'),
        ),
        migrations.AlterField(
            model_name='barrankcsv',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
